config/routes.rb
require 'subdomain'
require 'root'

Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  constraints(Subdomain) do
    devise_scope :user do
      get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    end

    match '/rimrock/:id',
          to: 'rimrock#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    match '/plgdata/:id',
          to: 'plgdata#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    match '/datanet/:repo_name/:id',
          to: 'datanet#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    get '/info', to: 'subdomains#info', as: :info
    get '/:id', to: 'subdomains#show', id: /.*/
  end

  constraints(Root) do
    devise_scope :user do
      get 'sign_in', to: 'home#index'
    end

    get '/dropbox/auth_finish',
        to: 'dropboxes#auth_finish',
        as: :dropbox_auth_finish

    get '/dropbox/webhook',
        to: 'dropboxes#webhook_verify'

    post '/dropbox/webhook',
         to: 'dropboxes#delta',
         as: 'dropbox_delta'

    resources :apps do
      member do
        get :download
        get :activity
        put :push
      end

      resource :deploy, only: [:show] do
        member do
          get :zip
          get :dropbox
        end
      end

      resources :app_members

      resource :dropbox, only: [:update, :destroy]
    end

    get 'help', to: 'help#show'
    get 'help/:category', to: 'help#show', as: 'help_file'

    # Sidekiq monitoring
    authenticate :user, lambda { |u| u.admin? } do
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
      namespace :admin do
        resource :job, only: :show
        resources :apps, only: [:index, :show, :update]
      end
    end
  end

  root 'home#index'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/apps/_activity.html.haml
%li
  .timeline-badge
    = icon('cloud-upload')
  .timeline-panel
    .timeline-heading
      %h4.timeline-title
        = activity.author.name
        %small
          = t("activity.#{activity.activity_type}")
          (#{time_ago_with_tooltip(activity.created_at)})
    .timeline-body
      - unless activity.message.blank?
        = activity.message

app/views/apps/_app_tab.html.haml
%h4
  = link_to root_url(subdomain: @app.full_subdomain) do
    = @app.name
    %span.text-muted (#{with_subdomain(@app.full_subdomain)}),
  = link_to root_url(subdomain: @app.dev_full_subdomain) do
    = t('apps.dev', name: @app.name)
    %span.text-muted (#{with_subdomain(@app.dev_full_subdomain)})
  .pull-right
    .btn-group
      - if can?(:edit, @app)
        = link_to [:edit, @app],
                  class: 'btn btn-sm btn-success',
                  title: t('apps.edit') do
          = icon('edit', t('edit'))
      - if can?(:destroy, @app)
        = link_to @app, method: :delete,
                  class: 'btn btn-sm btn-danger',
                  data: { confirm: t('apps.are_you_sure') },
                  title: t('apps.delete') do
          = icon('trash', t('delete'))
      - if can?(:download, @app) && @app.dev_files?
        = link_to [:download, @app],
                  class: 'btn btn-sm btn-default',
                  title: t('apps.download'),
                  data: { no_turbolink: true } do
          = icon('download', t('download'))
%hr

%ul.nav.nav-tabs#tabs1
  = nav_link(action: :show) do
    = link_to t('apps.login_tab'), @app
  - if can?(:deploy, @app)
    = nav_link(controller: :deploys) do
      = link_to t('apps.deploy_tab'), [@app, :deploy]
  = nav_link(controller: :app_members) do
    = link_to t('apps.members_tab'), [@app, AppMember]
  = nav_link(action: :activity) do
    = link_to t('apps.activity_tab'), [:activity, @app]

app/views/apps/_apps_menu.html.haml
%h2= t('apps.title')
%hr

= link_to new_app_path,
  class: 'btn btn-sm btn-create',
  title: t('apps.new') do
  = icon('plus', t('add_new'))

%ul.nav.nav-pills.nav-stacked.apps-nav
  - @apps.each do |app|
    = nav_tab(:id, :app_id, app.subdomain) do
      = link_to app do
        %h5{ style: 'word-wrap: break-word;' }
          = app.name
          %small
            = app.subdomain

app/views/apps/_form.html.haml
= simple_form_for app, html: { id: 'app_form' } do |f|
  = f.input :name
  = f.input :subdomain
  = f.input :login_text, input_html: { rows: 10 }
  = f.input :logo

app/views/apps/_welcome.html.haml
- if app.logo.blank?
  = icon('cubes', '', class: 'user-logo')
- else
  = image_tag(app.logo_url, class: 'user-logo')


.bs-docs-section
  %h1.page-header
    = app.name

  %p.text-center
    = markdown(app.login_text)

app/views/apps/activity.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      = render('app_tab')
      .tab-content
        .tab-pane.active.app-show-content
          %ul.timeline
            - @activities.each do |activity|
              = render('activity', activity: activity)

app/views/apps/deploy.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      = render('app_tab')
      .tab-content
        .tab-pane.active.app-show-content
          = link_to t('download'), [:download, @app]
          = link_to t('push'), [:push, @app], method: :put

          = simple_form_for @app do |f|
            = f.input :content
            = f.submit

app/views/apps/edit.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      %h4
        = t('apps.edit')
        .pull-right
          .btn-group
            %button#save-app.btn.btn-sm.btn-create{ title: t('apps.save') }
              = icon('save', t('save'))
            :javascript
              $(function() {
                $('#save-app').on('click', function() {
                  $('#app_form').submit();
                });
              });
            = link_to t('cancel'), @app,
                      class: 'btn btn-sm btn-default',
                      title: t('cancel')
      %hr

      = render('form', app: @app)

app/views/apps/index.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      %p.text-muted= t('apps.select')

app/views/apps/new.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      %h4
        = t('apps.create')
        .pull-right
          .btn-group
            %button#create-app.btn.btn-sm.btn-primary{ title: t('apps.create') }
              = icon('save', t('create'))
            :javascript
              $(function() {
                $('#create-app').on('click', function() {
                  $('#app_form').submit();
                });
              });

            = link_to t('cancel'), App,
                      class: 'btn btn-sm btn-default',
                      title: t('cancel')
      %hr

      = render('form', app: @app)

app/views/apps/show.html.haml
.row
  .col-md-3
    = render('apps_menu')
  .col-md-9
    .well
      = render('app_tab')
      .tab-content
        .tab-pane.active.app-show-content
          = render('welcome', app: @app)

app/views/apps/subdomain.html.haml
%h1
  = @app.name
  .pull-right.text-muted= @app.subdomain