config/routes.rb
require 'subdomain'
require 'root'

Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  constraints(Subdomain) do
    devise_scope :user do
      get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    end

    match '/rimrock/:id',
          to: 'rimrock#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    match '/plgdata/:id',
          to: 'plgdata#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    match '/datanet/:repo_name/:id',
          to: 'datanet#call',
          via: [:get, :post, :put, :delete],
          id: /.*/

    get '/info', to: 'subdomains#info', as: :info
    get '/:id', to: 'subdomains#show', id: /.*/
  end

  constraints(Root) do
    devise_scope :user do
      get 'sign_in', to: 'home#index'
    end

    get '/dropbox/auth_finish',
        to: 'dropboxes#auth_finish',
        as: :dropbox_auth_finish

    get '/dropbox/webhook',
        to: 'dropboxes#webhook_verify'

    post '/dropbox/webhook',
         to: 'dropboxes#delta',
         as: 'dropbox_delta'

    resources :apps do
      member do
        get :download
        get :activity
        put :push
      end

      resource :deploy, only: [:show] do
        member do
          get :zip
          get :dropbox
        end
      end

      resources :app_members

      resource :dropbox, only: [:update, :destroy]
    end

    get 'help', to: 'help#show'
    get 'help/:category', to: 'help#show', as: 'help_file'

    # Sidekiq monitoring
    authenticate :user, lambda { |u| u.admin? } do
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
      namespace :admin do
        resource :job, only: :show
        resources :apps, only: [:index, :show, :update]
      end
    end
  end

  root 'home#index'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/layouts/_flash.html.haml
.flash-container
  - if alert
    .flash-alert
      = alert
  - elsif notice
    .flash-notice
      = notice

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-md-2
        .footer-section
          %h5.text-uppercase
            = t('footer.contact.key')
          %p
            = t('footer.contact.mail')
      .col-md-3
        .footer-section
          %h5.text-uppercase
            = t('footer.address.key')
          %p
            = t('footer.address.line1')
            %br
            = t('footer.address.line2')
            %br
            = t('footer.address.line3')
      .col-md-2
        .footer-section
          %h5.text-uppercase
            = t('footer.links.key')
          %p
            = link_to t('footer.links.dice.name'), t('footer.links.dice.link')
            %br
            = link_to t('footer.links.cyfronet.name'), t('footer.links.cyfronet.link')
            %br
            = link_to t('footer.links.agh.name'), t('footer.links.agh.link')
      .col-md-5
        .footer-section
          %h5.text-uppercase
            = t('footer.about.key')
          %p
            = t('footer.about.desc')

app/views/layouts/_head.html.haml
%head
  %meta{charset: 'utf-8'}
  %meta{viewport: 'width=device-width, initial-scale=1.0'}
  %title= t 'title'

  = favicon_link_tag 'favicon.ico'
  = stylesheet_link_tag    'application'
  = javascript_include_tag 'application'
  = csrf_meta_tags

app/views/layouts/_navbar.html.haml
%header.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .locale.btn-group.btn-group-xs.navbar-btn
    = locale_link(:pl)
    = locale_link(:en)
  .container
    .navbar-header
      %button.navbar-toggle{:type => 'button', 'data-toggle' => 'collapse', 'data-target' => '.navbar-responsive-collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("navbar-logo2.png", :border=>0, id: 'navbar-logo'), root_path

    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li
          = nav_link(controller: :home) do
            = link_to t('code_name'), root_path
        - if user_signed_in?
          %li
            = nav_link(controller: [:apps, :deploys, :app_members]) do
              = link_to t('apps.title'), apps_path
          - if current_user.admin?
            = nav_link(controller: :admin_apps) do
              = link_to t('apps.admin.title'), admin_apps_path
            = nav_link(controller: :admin_jobs) do
              = link_to t('jobs.title'), admin_job_path
        %li
          = nav_link controller: :help do
            = link_to t('help.title'), help_path,
                      data: { placement: 'bottom' },
                      title: t('help.title')
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %a
              = current_user.name
          %li
            = link_to destroy_user_session_path,
                      data: { placement: 'bottom' },
                      title: t('logout'), method: :delete do
              = icon('sign-out')
        - else
          %li
            = link_to user_open_id_omniauth_authorize_path do
              = icon('sign-in', t('plgrid_sign_in'))

app/views/layouts/application.html.haml
!!! 5
%html
  = render 'layouts/head'
  %body
    = render 'layouts/navbar'
    .container{id: 'content'}
      = render 'layouts/flash'
      = yield
    = render 'layouts/footer'

app/views/layouts/devise.html.haml
!!! 5
%html
  = render 'layouts/head'
  %body
    = render 'layouts/app/navbar'
    .container{ id: 'app-content' }
      - if show_flash?
        = render 'layouts/flash'
      = yield
    = render 'layouts/app/footer'

app/views/layouts/errors.html.haml
!!! 5
%html
  = render 'layouts/head'
  %body
    .container.text-center
      = render 'layouts/flash'
      = yield